language: python
python:
  - "3.6.3"
sudo: required

install:
  - pip install flask

script:
  - python test.py

deploy:
  provider: heroku
  app: devopslab-helloworldd
  on:
    branch: master
  api_key:
    secure: Pes0zVbIWXf7B2ZdwiKOS0TTYWiBl40EK1SipEu8RY0AwiFWjm/NWI/srGCerGFUuPQbo+Yuo54lL7/9B69Do9ZRSsfv3a4tFE0C78Bf/ycyouA+M3x3hajsXtY+tM0XTsKQFieu+2y5/2MDE6Q73OLeEVYkYynACIEGwwhPzB0gA6fQZp+lwIc78B32a48zgj1FKkLjabF2IRI40bVheR4tiG3E3T/7cRL4/0DxbjeH0GddFJyFXHwZGgIrl66WMBNcHCzy0Xy5VfpKGxBUYwo5QHxOA/WZIwrzuV6XaZqKZouFZ4/nsxJWwhGxF3l0HUztvOz6p4TWYTAza6pKg0ooKSRID8kiFLe/tLp3BCI3i1DI4UTlod9r2fO40DyzpE+GmVD5OWQn+kVkmV0Ia0u4QVvuQjcSrj4yoOxkhJJnqpIbawnk970+Oi2neIvTZ6gauq1vvKs3mkWeFFhOsuZ9Xhly4NCBBbU+tH8EtvoJJrH5MgZMJ/qRplL052S6tDd4QjNKuSx0Dt1evVaPkrioa6jfE1e+0dlPSQJNY8N3OYn5O7rQXaUIsMTxVlDECDzOJwwlIPNqNL7I4hxGzn/ebNI2K9g3XWpN/4+BWZkwkk4ROhjkEKNC65uWNgMR0A1LzAw8ZcinBammN0k+tc8L2kSTJ+K9D7J2m3M1ryw=
notifications:
  email:
    on_success: never
    on_failure: never
